[package]
name = "ford"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.0", features = ["derive"] }
config = "0.15.11"
dialoguer = "0.11.0"
git2 = "0.20.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
